### ISSUE TITLE
Publish to the forge

### ISSUE THREAD

**Issue by roidelapluie** [dobbymoodge/puppet-acl#21]
I would like to see 0.0.3 published to the forge, thanks :-)

**Comment by roidelapluie** [comment]
See https://configdocs.web.cern.ch/configdocs/upstream/toforge.html to publish with travis. A good read

**Comment by dobbymoodge** [comment]
I'll look into this later this afternoon/tomorrow morning. Thanks for the
reminder!

**Comment by dobbymoodge** [comment]
doing this now; sorry for the delay

**Comment by dobbymoodge** [comment]
https://forge.puppetlabs.com/dobbymoodge/acl

**Comment by BEfelipe** [comment]
version 0.0.5 is not published on the forge.
