### ISSUE TITLE
module name conflict

### ISSUE THREAD

**Issue by claflico** [dobbymoodge/puppet-acl#26]
FYI there was already a module that used acl as its folder name: puppetlabs/acl

That module is needed for managing perms on Windows so this is creating a conflict when both Linux and Windows nodes are managed by the same puppetmaster.

**Comment by dobbymoodge** [comment]
@roidelapluie I'm a bit concerned about breaking changes here - we'll need to rename the repository won't we? e.g. puppet-posix_acl or similar?

**Comment by dobbymoodge** [comment]
@roidelapluie bad news, AFAICT:

> 2016-10-27 16:39:06     jolamb_ I maintain a puppet module that I want/need to change the module name of. Is there some way for me to do that without breaking existing users?
> 2016-10-27 17:00:12     rnelson0        jolamb_: release one last version and in the readme say "this module is being replaced by <newnamespace>/<newname>", then release a version in that namespace.
> 2016-10-27 17:00:40     jolamb_ rnelson0: eesh
> 2016-10-27 17:00:47     rnelson0        I would set the old namespace's version to 999.999.999 so it is extremely noticeable
> 2016-10-27 17:01:21     jolamb_ rnelson0: I host it on github, so I reckon for users that pull it from there I will need to also rename the repo - or possibly move it to a new repository?
> 2016-10-27 17:01:24     rnelson0        rnelson0/oldthing 2.0.0 -> 999.999.999, then projectname/newthing 2.0.0
>

**Comment by ekohl** [comment]
With #33 merged I think this can be closed.

**Comment by vandelin586** [comment]
Well the module still gets dropped into my pupept server as folder named acl. I may not be correct in this but wasn't this the original issue? puppetlabs-acl drops the same folder name within your module directory which creates a conflict?

**Comment by ekohl** [comment]
@vandelin586 that should be fixed once we transfer to voxpupuli and do a release with the new name. For now you should ensure you have a git clone that's checked out to the correct directory.

**Comment by dobbymoodge** [comment]
Belated closing re: @ekohl comment
